DB_HOST: localhost
DB_PORT: 5432
DB_USERNAME: postgres
DB_PASSWORD: 12345
DB_NAME: foundation

JWT_ACCESS_SECRET_KEY: "VGhlIGRlZmF1bHQgdW5zZWN1cmUgc3RyaW5nIHVzZWQgZm9yIC5lbnYuZGV2IGNvbmZpZyBhcyBKV1RfQUNDRVNTX1NFQ1JFVF9LRVk="
JWT_REFRESH_SECRET_KEY: "VGhlIGRlZmF1bHQgdW5zZWN1cmUgc3RyaW5nIHVzZWQgZm9yIC5lbnYuZGV2IGNvbmZpZyBhcyBKV1RfUkVGUkVTSF9TRUNSRVRfS0VZ"

# 15 Min
JWT_ACCESS_SECRET_EXPIRY_MS: 900000

# 1 Hour
JWT_REFRESH_SECRET_EXPIRY_MS: 3600000